#A list of block IDs and tags that should be affected by this definition.
#Entries can be supplied in the below formats:
#	Namespaces:   '<minecraft>'
#	Tags:         '#forge:stone'
#	IDs:          'minecraft:stone'
Blocks = ["minecraft:andesite_slab", "minecraft:blackstone_slab", "minecraft:cobbled_deepslate_slab", "minecraft:cobblestone_slab", "minecraft:cut_copper_slab", "minecraft:cut_red_sandstone_slab", "minecraft:cut_sandstone_slab", "minecraft:dark_prismarine_slab", "minecraft:deepslate_tile_slab", "minecraft:diorite_slab", "minecraft:exposed_cut_copper_slab", "minecraft:granite_slab", "minecraft:mossy_cobblestone_slab", "minecraft:oxidized_cut_copper_slab", "minecraft:polished_andesite_slab", "minecraft:polished_blackstone_slab", "minecraft:polished_deepslate_slab", "minecraft:polished_diorite_slab", "minecraft:polished_granite_slab", "minecraft:prismarine_slab", "minecraft:purpur_slab", "minecraft:quartz_slab", "minecraft:red_sandstone_slab", "minecraft:sandstone_slab", "minecraft:smooth_quartz_slab", "minecraft:smooth_red_sandstone_slab", "minecraft:smooth_sandstone_slab", "minecraft:smooth_stone_slab", "minecraft:stone_slab"]

[Physics]
	#The maximum weight the block(s) can support both horizontally and vertically.
	#Range: > 0
	SupportStrength = 44010

	#Additional support strength to apply to the amount of weight the block(s) can support above when acting as a beam.
	#A value of 1.0 will allow the block(s) to support an infinite amount of weight, whereas a value of 0.0 will not apply any additional strengthening.
	#Range: 0.0 ~ 1.0
	BeamStrength = 0.6

	#The mass of the block(s), in kilograms.
	#Range: 1.0 ~ 50000.0
	Mass = 600.0

	#Whether the block(s) can hang from other blocks for support.
	CanHang = true

	#Whether the block(s) can attach to the sides of other blocks for support.
	CanAttach = true

	#Whether the block(s) can diagonally attach to other blocks for support.
	CanAttachDiagonally = false

	#The chance the block(s) will slide after falling and landing.
	#Range: 0.0 ~ 1.0
	SlideChance = 0.5

	#An additional "dice roll" to apply to the base slide chance of the block(s), when being placed by an entity.
	#Setting a value of 1.0 means the slide chance will remain unaffected.
	#Range: 0.0 ~ 1.0
	PlacementSlideModifier = 0.0

	#A multiplier to apply to the damage caused by the block(s) when falling on entities.
	#Range: 0.0 ~ 10.0
	EntityDamageScale = 1.0

	#Whether the block(s) should break instead of falling.
	BreaksOnFalling = false

	#The maximum force the block(s) can withstand before being broken.
	#Range: > 0
	Strength = 391200

	#Whether the block(s) can be supported by liquids that are below.
	FloatsOnLiquid = false

	#This section allows you to extend the collision bounds for each specific face of the block(s).
	#Note: Directions are relative to the orientation of the block(s) (excluding vertical axis), not the world itself.
	[Physics.ExtendedCollisionBounds]
		#Fully extends the collision bounds of the block(s) in the UP direction.
		Up = false

		#Fully extends the collision bounds of the block(s) in the DOWN direction.
		Down = false

		#Fully extends the collision bounds of the block(s) in the NORTH direction.
		North = false

		#Fully extends the collision bounds of the block(s) in the EAST direction.
		East = false

		#Fully extends the collision bounds of the block(s) in the SOUTH direction.
		South = false

		#Fully extends the collision bounds of the block(s) in the WEST direction.
		West = false

[ChunkAnalysis]
	#Whether the block(s) should be processed during chunk analysis updates.
	Enabled = true

