
[FX]
	#Avaible, repeat, fast repeat, big explode
	boss_death_mode = "big explode"
	#Blood in mobs like skeletons or iron golems.
	blood_nflesh = false
	ribs_hurt_half = true
	blood_hurt_half = false
	#Avaible, explosive
	brutal_hurt = "explosive"

["Particles configuration"]
	xz_area_size = 0.2
	y_area_size = 0.7
	particle_multiplicator = 1.3
	particle_speed_multiplicator = 0.4
	#(Y +)
	center_y_mob = 1.0
	center_y_player = 1.0
	bones_particles_multiplicator = 5.0
	bones_particles_speed_multiplicator = 2.0

