debug = false
disable_crowdin = false
check_for_updates = true

key_bindings = []


[addons.pv-addon-soundphysics]
"gui.plasmovoice.soundphysics.mic_reverb_volume" = 1.0
"gui.plasmovoice.soundphysics.enabled" = true
"gui.plasmovoice.soundphysics.mic_reverb" = true

[voice]
disabled = false
microphone_disabled = false
activation_threshold = -30.0
input_device = ""
output_device = ""
disable_input_device = false
use_javax_input = false
microphone_volume = 1.0
noise_suppression = false
volume = 1.0
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = false
stereo_capture = false

[voice.volumes.source_9a7e7345-6500-4e52-b516-5d781a0e46ca]
volume = 1.0
[voice.volumes.source_9b164fe0-ba3b-4af3-87e9-698d021e76d1]
volume = 1.0
[voice.volumes.source_e40ad6a6-4f59-4974-8b6d-7b9a4bc5aed7]
volume = 1.0
[voice.volumes.source_9ea69569-eb67-4da8-8313-af219130a739]
volume = 1.0
[voice.volumes.proximity]
volume = 1.0
[voice.volumes.source_0b69fc5d-34a8-4a1b-a682-e8b024b6bdeb]
volume = 1.0
[voice.volumes.source_996aad26-0612-4911-8139-249d0598dd5d]
volume = 1.0
[voice.volumes.source_10e8f56c-616d-48e8-803d-cd0b44f47c83]
volume = 1.0
[voice.volumes.source_4c247c68-f1d9-4ea2-8834-548286ed204f]
volume = 1.0
[voice.volumes.source_77b5cce3-e18e-40b5-b341-8c3f13ea4654]
volume = 1.0

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
proximity = "OFF"
